### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by lukasbystricky** [ACBSmith/george-grey_polynesian-mythology#1]
For appendix-1, see the SEMoS guidelines on [bridgeheads](https://standardebooks.org/manual/1.8.0/single-page#7.2.11). Specifically the bridgehead should be in sentence case, in normal font. 

If you think a section doesn't belong in the ToC, then you can follow rule [7.2.10.8](https://standardebooks.org/manual/1.8.0/single-page#7.2.10.8).

For the notation in appendix-1, I think your solution is fine. The alternative would be to create an SVG for each symbol. I believe that's been done elsewhere (I can't remember where exactly), but that may be an overkill here. 

The blockquote in appendix-1 looks like a footer to me, and should be styled as usual, so no need to centre it. 

See SEMoS [5.8.2 ](https://standardebooks.org/manual/1.8.0/single-page#5.8.2) for how to handle the `cite` element in appendix-2. I think what you have looks good, except maybe you can get rid of the trailing period.

Since "firstborn" is in MW, I would argue that "lastborn" is fine as a single word, but it's up to you. Whatever you decide, just make sure it's consistent and any change you make is editorial.

I don't think the square brackets in chapter-2 should be moved, I think that's fine as is. There's probably a stronger argument for moving the one in chapter-16, but again, I think it's fine as is.

For the page reference in endnote-12, you can add an id to the paragraph (see  SEMoS [5.1.2.8](https://standardebooks.org/manual/1.8.0/single-page#5.1.2.8)) and link to that. Change the endnote text to "See here" or something similar. There are several examples, e.g. note-18 [here](https://github.com/lukasbystricky/mary-parker-follett_the-new-state/blob/main/src/epub/text/endnotes.xhtml). I would do the same thing for note-50. 

No need to expand G. G., but it should be tagged as a personal-name.

For note-26, normally we just use the latest edition, but if you think the extra information is important that's fine. Make sure this was done in an editorial commit, and add a remark in the production notes.

For the blockquote in preface-2, if you think it's an unordered list, you can use a `<ul>` (see SEMoS [5.6](https://standardebooks.org/manual/1.8.0/single-page#5.6)).

You're correct about MSS. This is an example given in SEMoS [8.10.9.3](https://standardebooks.org/manual/1.8.0/single-page#8.10.9.3).

**Comment by ACBSmith** [comment]
### Addressed
Leaving the bridgehead casing as-is. I have added a pseudo-selector to stop the css that applies to the mid-appendix headers also applying to the bridgehead, which had been a problem.

Have removed those sections from the ToC as per that rule. It is causing some lint errors, so I have added them to the lint-ignore.

Sounds good with the notation. Leaving as-is.

Have removed trailing periods from cite elements.

I have added the link to endnote-12 based on that example. I have not done so for endnote-50 as it is intended to link to the start of the chapter.

Made G.G. a personal name.

Added the endnote-26 note to the production notes.

Noted about MSS.

### Outstanding
Leaving the square brackets as-is. Only other questions is if they should be converted to parentheses?

Converted to a `<ul>`, but I'm not sure that it should have bullets. Should I target this with CSS, or leave as-is with the bullets in place?

Have converted it to a footer in appendix-1. As it's not a sender of a letter, I have not given it those semantic elements. However, it is now kicking up a lint error.
